version: "3"

services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports: 
          - "80:80"
          - "443:443"
        volumes:
          - ./Backend:/srv/docker-server
          - ./log:/var/log/nginx
          - ./Backend/static:/srv/docker-server/static
        depends_on:
          - django

    django:
        container_name: django
        build: ./Backend
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./Backend:/srv/docker-server
          - ./log:/var/log/uwsgi

