version: "3"

services:
    deploy:
        build:
          dockerfile: Dockerfile
          context: ./Deploy
        container_name: deploy
        volumes:
          - /app/node_modules
          - ./Deploy:/app
        stdin_open: true
        ports:
          - 3000:3000

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports: 
          - "80:80"
          - "443:443"
        volumes:
          - ./Backend:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./Backend
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./Backend:/srv/docker-server
          - ./log:/var/log/uwsgi

