version: "3"

services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports: 
          - "80:80"
        volumes:
          - ./Backend:/docker/jenkins-data/workspace/s04p23b105/Backend
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./Backend
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./Backend:/docker/jenkins-data/workspace/s04p23b105/Backend
          - ./log:/var/log/uwsgi